export const LEVEL_NAMES: Record<number, string> = {
  1: "Morning Run",
  2: "Speed Surprise",
  3: "Kelp Garden",
  4: "First Market",
  5: "Candy Discovery",
  6: "Speed Test",
  7: "Chest Delight",
  8: "Moonfall",
  9: "Weight Pressure",
  10: "Golden Level",
  11: "Anchor Trap",
  12: "Lava Temptation",
  13: "Breather",
  14: "Tide Storm",
  15: "Coral Hell",
  16: "Leaf Whisper",
  17: "Skeleton Night",
  18: "Whirlpool Rises",
  19: "Last Breath",
  20: "BOSS: Cove Queen",
  21: "Coral Shock",
  22: "Double Coral",
  23: "Speed Hell",
  24: "Breather",
  25: "Galaxy Gate",
  26: "Skeleton Corridor",
  27: "Double Whirlpool",
  28: "Rod Trial",
  29: "Breather",
  30: "BOSS: Golden Coral",
  31: "Deep Opening",
  32: "Capacity Crisis",
  33: "Rain Trap",
  34: "Breather",
  35: "King Whisper",
  36: "Dark Depths",
  37: "Mushroom Dance",
  38: "Galaxy Hunt",
  39: "Final Move",
  40: "BOSS: Deep Blue Beast",
  41: "Storm Gate",
  42: "Double Skeleton",
  43: "Capacity Shock",
  44: "Breather",
  45: "King Season",
  46: "Dark Corridor",
  47: "Mushroom Forest",
  48: "Galaxy Storm",
  49: "Final Trial",
  50: "BOSS: Storm Lord",
  51: "Aurora Opening",
  52: "Dark Hunt",
  53: "Breather",
  54: "King Surge",
  55: "Coral Labyrinth",
  56: "Warp War",
  57: "Silent Danger",
  58: "Aurora Storm",
  59: "Chaos Night",
  60: "BOSS: Aurora Dragon",
  61: "Crimson Moon",
  62: "Curse: Heavy Waters",
  63: "Curse: Fast Current",
  64: "Breather",
  65: "Curse: Blind Spot",
  66: "Curse: Reverse Current",
  67: "Curse: Double Damage",
  68: "Breather",
  69: "Curse: Economic Crisis",
  70: "BOSS: Crimson Moon Beast",
  71: "Dimension Gate",
  72: "Curse: Chain Reaction",
  73: "Curse: Invisible Fish",
  74: "Breather",
  75: "Curse: Countdown",
  76: "Curse: Reverse Market",
  77: "Curse: Skeleton Army",
  78: "Breather",
  79: "Everything Active",
  80: "BOSS: Chaos Lord",
  81: "Golden Darkness",
  82: "Combined Curse I",
  83: "Combined Curse II",
  84: "Breather",
  85: "Curse: Time Pressure",
  86: "Curse: Reverse Weight",
  87: "Curse: Fish Escape",
  88: "Breather",
  89: "All Curses",
  90: "BOSS: Golden Dragon",
  91: "The Final Voyage Begins",
  92: "Curse: Time Bomb",
  93: "Curse: Dark Matter",
  94: "Last Breath",
  95: "Combined Curse: Final I",
  96: "Combined Curse: Final II",
  97: "Combined Curse: Final III",
  98: "Silent Storm",
  99: "One Chance",
  100: "FINAL BOSS: Legend Lord"
};
