import { t } from '@/lib/i18n';

export const LEVEL_NAMES: Record<number, string> = {
  1: t('levels.1', "Morning Run"),
  2: t('levels.2', "Speed Surprise"),
  3: t('levels.3', "Kelp Garden"),
  4: t('levels.4', "First Market"),
  5: t('levels.5', "Candy Discovery"),
  6: t('levels.6', "Speed Test"),
  7: t('levels.7', "Chest Delight"),
  8: t('levels.8', "Moonfall"),
  9: t('levels.9', "Weight Pressure"),
  10: t('levels.10', "Golden Level"),
  11: t('levels.11', "Anchor Trap"),
  12: t('levels.12', "Lava Temptation"),
  13: t('levels.13', "Breather"),
  14: t('levels.14', "Tide Storm"),
  15: t('levels.15', "Coral Hell"),
  16: t('levels.16', "Leaf Whisper"),
  17: t('levels.17', "Skeleton Night"),
  18: t('levels.18', "Whirlpool Rises"),
  19: t('levels.19', "Last Breath"),
  20: t('levels.20', "BOSS: Cove Queen"),
  21: t('levels.21', "Coral Shock"),
  22: t('levels.22', "Double Coral"),
  23: t('levels.23', "Speed Hell"),
  24: t('levels.24', "Breather"),
  25: t('levels.25', "Galaxy Gate"),
  26: t('levels.26', "Skeleton Corridor"),
  27: t('levels.27', "Double Whirlpool"),
  28: t('levels.28', "Rod Trial"),
  29: t('levels.29', "Breather"),
  30: t('levels.30', "BOSS: Golden Coral"),
  31: t('levels.31', "Deep Opening"),
  32: t('levels.32', "Capacity Crisis"),
  33: t('levels.33', "Rain Trap"),
  34: t('levels.34', "Breather"),
  35: t('levels.35', "King Whisper"),
  36: t('levels.36', "Dark Depths"),
  37: t('levels.37', "Mushroom Dance"),
  38: t('levels.38', "Galaxy Hunt"),
  39: t('levels.39', "Final Move"),
  40: t('levels.40', "BOSS: Deep Blue Beast"),
  41: t('levels.41', "Storm Gate"),
  42: t('levels.42', "Double Skeleton"),
  43: t('levels.43', "Capacity Shock"),
  44: t('levels.44', "Breather"),
  45: t('levels.45', "King Season"),
  46: t('levels.46', "Dark Corridor"),
  47: t('levels.47', "Mushroom Forest"),
  48: t('levels.48', "Galaxy Storm"),
  49: t('levels.49', "Final Trial"),
  50: t('levels.50', "BOSS: Storm Lord"),
  51: t('levels.51', "Aurora Opening"),
  52: t('levels.52', "Dark Hunt"),
  53: t('levels.53', "Breather"),
  54: t('levels.54', "King Surge"),
  55: t('levels.55', "Coral Labyrinth"),
  56: t('levels.56', "Warp War"),
  57: t('levels.57', "Silent Danger"),
  58: t('levels.58', "Aurora Storm"),
  59: t('levels.59', "Chaos Night"),
  60: t('levels.60', "BOSS: Aurora Dragon"),
  61: t('levels.61', "Crimson Moon"),
  62: t('levels.62', "Curse: Heavy Waters"),
  63: t('levels.63', "Curse: Fast Current"),
  64: t('levels.64', "Breather"),
  65: t('levels.65', "Curse: Blind Spot"),
  66: t('levels.66', "Curse: Reverse Current"),
  67: t('levels.67', "Curse: Double Damage"),
  68: t('levels.68', "Breather"),
  69: t('levels.69', "Curse: Economic Crisis"),
  70: t('levels.70', "BOSS: Crimson Moon Beast"),
  71: t('levels.71', "Dimension Gate"),
  72: t('levels.72', "Curse: Chain Reaction"),
  73: t('levels.73', "Curse: Invisible Fish"),
  74: t('levels.74', "Breather"),
  75: t('levels.75', "Curse: Countdown"),
  76: t('levels.76', "Curse: Reverse Market"),
  77: t('levels.77', "Curse: Skeleton Army"),
  78: t('levels.78', "Breather"),
  79: t('levels.79', "Everything Active"),
  80: t('levels.80', "BOSS: Chaos Lord"),
  81: t('levels.81', "Golden Darkness"),
  82: t('levels.82', "Combined Curse I"),
  83: t('levels.83', "Combined Curse II"),
  84: t('levels.84', "Breather"),
  85: t('levels.85', "Curse: Time Pressure"),
  86: t('levels.86', "Curse: Reverse Weight"),
  87: t('levels.87', "Curse: Fish Escape"),
  88: t('levels.88', "Breather"),
  89: t('levels.89', "All Curses"),
  90: t('levels.90', "BOSS: Golden Dragon"),
  91: t('levels.91', "The Final Voyage Begins"),
  92: t('levels.92', "Curse: Time Bomb"),
  93: t('levels.93', "Curse: Dark Matter"),
  94: t('levels.94', "Last Breath"),
  95: t('levels.95', "Combined Curse: Final I"),
  96: t('levels.96', "Combined Curse: Final II"),
  97: t('levels.97', "Combined Curse: Final III"),
  98: t('levels.98', "Silent Storm"),
  99: t('levels.99', "One Chance"),
  100: t('levels.100', "FINAL BOSS: Legend Lord")
};
